### ISSUE TITLE
can't Choose Window Channel

### ISSUE THREAD

**Issue by garfield2412** [j-a-n/homematic-addon-velux#1]
Drop down list is empty! for all possible 4 channels.
Version installed 0.97 (showing 0.96?)
Any help?
Like the idea of the Programm!

![1](https://user-images.githubusercontent.com/33608374/32703894-f24a4c3c-c7fc-11e7-9a5d-cff5e30f8669.jpg)
![2](https://user-images.githubusercontent.com/33608374/32703896-f70fa866-c7fc-11e7-9fb1-677d2734197b.jpg)

**Comment by j-a-n** [comment]
Thanks for reporting, should be fixed with version 0.9.8
