### ISSUE TITLE
can't add Window anyway (V0.9.8)

### ISSUE THREAD

**Issue by garfield2412** [j-a-n/homematic-addon-velux#2]
Installed V 0.9.8 and Version number changed to 0.9.8
File Index.htm changed also (Date: 13.11.2017 10:53:44)

But issue stays there (no channel selectable and no KEY for UP/DOWN selectable)

Using HM-LC-Sw4-Ba-PCB to control Velux FB. Working fine without the addon.

maybee this helps (cuxd during installation)
Nov 13 22:41:44 homematic-ccu2 daemon.info cuxd[358]: write_pid /var/run/cuxd.pid [358]
Nov 13 22:41:44 homematic-ccu2 daemon.info cuxd[358]: CUx-Daemon(1.11a) on CCU(2.29.23) start PID:358
Nov 13 22:41:44 homematic-ccu2 daemon.info cuxd[358]: load paramsets(/usr/local/addons/cuxd/cuxd.ps) size:2590 update(-49s):Mon Nov 13 22:40:55 2017
Nov 13 22:41:44 homematic-ccu2 daemon.info cuxd[358]: write_proxy /var/cache/cuxd_proxy.ini (358 /usr/local/addons/cuxd/ 1.11a 2.29.23 0)
Nov 13 22:41:44 homematic-ccu2 daemon.info cuxd[358]: add interface 'CUxD'
Nov 13 22:41:44 homematic-ccu2 daemon.info cuxd[358]: write 4 interfaces to /usr/local/etc/config/InterfacesList.xml
Nov 13 22:44:20 homematic-ccu2 daemon.warn cuxd[358]: process_rpc_request(127.0.0.1) - illegal XMLRPC(listDevices) request
Nov 13 22:44:49 homematic-ccu2 daemon.warn cuxd[358]: process_rpc_request(127.0.0.1) - illegal XMLRPC(init) request
Nov 13 22:46:42 homematic-ccu2 daemon.info cuxd[358]: INIT 'xmlrpc_bin://127.0.0.1:1999' '1321

**Comment by j-a-n** [comment]
Could you please provide the response of:
`http://<your-ccu-ip>/addons/velux/rest.cgi?/get_channels`

**Comment by garfield2412** [comment]
http://192.168.4.24/addons/velux/rest.cgi?/get_channels 

=

{"in":[],"out":[],"cuxd":[]}

**Comment by j-a-n** [comment]
Please run the following rega script in WebUI:
```
string deviceid;
foreach(deviceid, dom.GetObject(ID_DEVICES).EnumUsedIDs()) {
   var device = dom.GetObject(deviceid);
   WriteLine("Name: " # device.Name());
   WriteLine("Interface: " # device.Interface());
   string interfaceid = device.Interface();
   var interface = dom.GetObject(interfaceid);
   WriteLine("Interface: " # interface.Name());
   string channelid;
   foreach(channelid,device.Channels().EnumUsedIDs()) {
      var channel = dom.GetObject(channelid);
      WriteLine("channel.Address: " # channel.Address());
      WriteLine("channel.ChnLabel: " # channel.ChnLabel());
      WriteLine("channel.ChnDirection: " # channel.ChnDirection());
      WriteLine("channel.Name: " # channel.Name());
      WriteLine("--");
   }
   WriteLine("");
}
```
Then please provide ChnLabel and ChnDirection of one of your output channels of the HM-LC-Sw4-Ba-PCB device.

**Comment by garfield2412** [comment]
### Name: Roll Schlafzimmer Dachfenster links
Interface: 1009
Interface: BidCos-RF
channel.Address: OEQ0097258:1
**channel.ChnLabel: SWITCH
channel.ChnDirection: 2**
channel.Name: **Roll SZ DF links runter** (in english: "DOWN")
--
channel.Address: OEQ0097258:2
channel.ChnLabel: SWITCH
channel.ChnDirection: 2
channel.Name: **Roll SZ DF links Stop**  (in english: "STOP")
--
channel.Address: OEQ0097258:3
channel.ChnLabel: SWITCH
channel.ChnDirection: 2
channel.Name: Roll SZ DF links hoch ( (in english: "UP")
--

(not used)

channel.Address: OEQ0097258:4
channel.ChnLabel: SWITCH
channel.ChnDirection: 2
channel.Name: HM-LC-Sw4-Ba-PCB OEQ0097258:4
--

**Comment by j-a-n** [comment]
Thank you, I added the SWITCH a s output device.
Please try version 0.9.9
You won't need the STOP channel.

**Comment by garfield2412** [comment]
okay, i can choose the channels now.
but there are some issues...
1. after i added the window/shutter the addon tells me: windows succesfully added - but the entry list stays empty (can't Change anything later)
2. i only have Shutters - no Window Motor, so i have to configure a motor instead of a shutter - otherwise there are red fields :-)

**Comment by j-a-n** [comment]
Okay, I just made the window parameters optional.
So please try to create a window with version 0.9.10.
You will have to fill in a name and all the Shutter parameters.

**Comment by garfield2412** [comment]
okay! so far so good, excelent work! No 1 is working :-)

But i configured a second shutter. Also showed "window succesfully added" but it doesn't Show up in the window list as no 2.

**Comment by j-a-n** [comment]
Without any error message?
Is there an error in the browser Console?

**Comment by garfield2412** [comment]
okay.. updatet no 2 values once again and "update sucessfull" showed up and no 2 was visible.

Awesome! Both shutter working fine. Some delay, but that's not an issue of your addon - i think.

Thank you so much !

**Comment by garfield2412** [comment]
only one little optical thing ( not sure if you can fix this or if it's "wired" as it is in Homematic/tynymatic)
in the android app "tinymatic" the virtual shutter is shown as "short/long" button and not as a value field 0-100% as a "normal" shutter.
but it think you can't Change this becaus of the way this thing is working...

**Comment by j-a-n** [comment]
Which "Control" did you choose in CUxD 16-channel universal control device?
You should use BLIND (Jalousie).

**Comment by garfield2412** [comment]
yes, "Blind"!
![1](https://user-images.githubusercontent.com/33608374/32854021-875ca8a0-ca3d-11e7-9698-27c81953a6cd.jpg)

**Comment by j-a-n** [comment]
Then, it seems to be a problem with the app. Home24 and Webmatic are working flawlessly with the virtual Blind.
